server:
  address: 127.0.0.1
  port: 3535
spring:
  datasource:
    url: jdbc:mysql://192.168.44.132:3306/cyn
    username: caiyn
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    cache: false #关闭缓存
    prefix: classpath:/templates/ #调整页面路径
logging:
  path: D:\\logs
#shiro:
#  filterChainDefinitionMap:
#    /logout: logout
#    /**: authc
#    /index2: anon
