server:
  address: 127.0.0.1
  port: 3535
spring:
  datasource:
    url: jdbc:mysql://192.168.44.132:3306/cyn
    username: caiyn
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    cache: false #关闭缓存
    prefix: classpath:/templates/ #调整页面路径
  redis:
    host: 192.168.44.132
    port: 36379
    password: 123456
    jedis:
      pool:
        max-idle: 20
        min-idle: 20
        max-active: 200
        max-wait: 1000ms
logging:
  path: D:\\logs
#shiro:
#  filterChainDefinitionMap:
#    /logout: logout
#    /**: authc
#    /index2: anon
